refresh_recordings:
  fields:
    entry_id:
      selector:
        text:
download_recording:
  fields:
    entry_id:
      selector:
        text:
    file_name:
      required: true
      selector:
        text:
    target_name:
      selector:
        text:
drive:
  fields:
    entry_id:
      selector:
        text:
    lx:
      selector:
        number:
          min: -1.0
          max: 1.0
          step: 0.05
    ly:
      selector:
        number:
          min: -1.0
          max: 1.0
          step: 0.05
    rx:
      selector:
        number:
          min: -1.0
          max: 1.0
          step: 0.05
    ry:
      selector:
        number:
          min: -1.0
          max: 1.0
          step: 0.05
stop:
  fields:
    entry_id:
      selector:
        text:
command:
  fields:
    entry_id:
      selector:
        text:
    opcode:
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
